[project]
name = "uao-neumonia"
version = "0.1.0"
description = "Herramienta para la detección de neumonía en radiografías de tórax mediante Deep Learning y Grad-CAM"
readme = "README.md"
authors = [
    { name = "Cesar Carabali", email = "cesar_and.carabali@uao.edu.co" }
]
requires-python = ">=3.13"
dependencies = [
    "img2pdf>=0.6.3",
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pyautogui>=0.9.54",
    "pydicom>=3.0.2",
    "python-xlib>=0.33",
    "tensorflow>=2.21.0",
    "tkcap>=0.0.4",
]

[tool.uv]
package = false